Add URL Trim Query UDF
GoogleCloudPlatform/bigquery-utils pull request #279
Opened 2022-01-28 15:27 UTC by 1987yama3

I implement a BigQuery UDF to trim URL query parameter. 
For example, in Google Analytics 4 BigQuery, the "page_location" parameter store full query parameter. 
However, in the context of web analytics, there is a need to exclude some query parameter for analytics.

Excluding them with Standard Function is complicated, so I implemented UDF.

Thanks

2022-01-31 21:41 UTC, danieldeleo commented
/gcbrun

2022-02-01 14:56 UTC, danieldeleo commented on udfs/community/test_cases.js
> +generate_udf_test("url_trim_query", [
Add test cases for NULL inputs and a test case for url which contains keys but no hash

2022-02-01 16:40 UTC, danieldeleo requested changes
Thanks for creating this PR. I think it would be better to keep UDFs in SQL syntax if possible since they'll be more performant. I've created an example below which I think should provide the same functionality as your JS UDF. 


`CREATE TEMP FUNCTION url_trim_keys(url STRING, keys_to_trim ARRAY<STRING>) AS ((

SELECT 
    url_base || IF(keys IS NULL, '', '?' || keys) || IF(url_hash IS NULL, '', '#' || url_hash)
FROM(
    SELECT 
        url_base,
        url_hash,
        STRING_AGG(
            IF(LOWER(SPLIT(url_key, '=')[SAFE_OFFSET(0)]) NOT IN(SELECT LOWER(key) FROM UNNEST(keys_to_trim) AS key),
                url_key,
                NULL),
            '&') AS keys
    FROM(
        SELECT
            SPLIT(url, '?')[SAFE_OFFSET(0)] AS url_base,
            SPLIT(url, '#')[SAFE_OFFSET(1)] AS url_hash,
            IFNULL(SPLIT(SPLIT(SPLIT(url, '?')[SAFE_OFFSET(1)], '#')[SAFE_OFFSET(0)], '&'), [CAST(NULL AS STRING)]) AS url_keys
    ), UNNEST(url_keys) AS url_key
    GROUP BY 1,2)
));

SELECT url_trim("https://www.example.com/abc/index.html?id=12345&utm_id=abc123&hello=world", ["utm_id", "id"])
UNION ALL
SELECT url_trim("https://www.example.com/abc/index.html?id=12345&utm_id=abc123",["utm_id"])
UNION ALL        
SELECT url_trim("https://www.example.com/abc/index.html?id=12345&utm_id=abc123",["utm_id", "id"])
UNION ALL       
SELECT url_trim( "https://www.example.com/abc/index.html?id=12345&utm_id=abc123#hash", ["utm_id"])
UNION ALL
SELECT url_trim("https://www.example.com/abc/index.html?id=12345&utm_id=abc123#hash", ["utm_id", "id"])
UNION ALL       
SELECT url_trim("https://www.example.com/abc/index.html", ["gclid"])`

2022-02-02 02:58 UTC, 1987yama3 commented
@danieldeleo Thanks for your comment. It is nice code! I change to SQL Syntax from JS. Please check this.

2022-02-02 14:41 UTC, danieldeleo commented on udfs/community/url_trim_query.sqlx
> + * Copyright 2019 Google LLC
```suggestion
 * Copyright 2022 Google LLC
```

2022-02-02 14:46 UTC, danieldeleo commented on udfs/community/test_cases.js
> +
```suggestion
```

2022-02-02 14:47 UTC, danieldeleo commented on udfs/community/test_cases.js
> +])
```suggestion
]);
```

2022-02-02 14:47 UTC, danieldeleo commented on udfs/community/test_cases.js
> +            `["hellp"]`
```suggestion
            `["hello"]`
```

2022-02-02 14:49 UTC, danieldeleo commented on udfs/community/README.md
> +### [url_trim_query(urlString STRING, keys ARRAY<STRING>)](url_trim_query.sqlx)
```suggestion
### [url_trim_query(url STRING, keys_to_trim ARRAY<STRING>)](url_trim_query.sqlx)
```

2022-02-02 14:56 UTC, danieldeleo commented on udfs/community/README.md
> +Returns trimed query URL from input URL. The remove query is specified arguments.
```suggestion
Returns a URL with specified keys removed from the
[URL's query component](https://en.wikipedia.org/wiki/Query_string). 
The keys to be removed are provided as an ARRAY<STRING> input argument.
```

2022-02-03 05:21 UTC, 1987yama3 commented on udfs/community/url_trim_query.sqlx
> + * Copyright 2019 Google LLC
Thanks

2022-02-03 05:21 UTC, 1987yama3 commented
@danieldeleo Thanks. I fixed according to the code review. Please check it.

2022-02-03 14:59 UTC, danieldeleo approved these changes
Thanks for the quick turnaround!

2022-02-03 15:00 UTC, merged