Add CompilerWorks UDFs
GoogleCloudPlatform/bigquery-utils pull request #300
Opened 2022-09-04 10:33 UTC by rajc242

CompilerWorks UDFs are added to community UDFs.

2022-09-13 20:31 UTC, danieldeleo commented on udfs/community/cw_array_compact.sqlx
> + * Copyright 2019 Google LLC
```suggestion
 * Copyright 2022 Google LLC
```

2022-09-13 20:31 UTC, danieldeleo commented on udfs/community/cw_array_compact.sqlx
> + * Copyright 2019 Google LLC
Update all other files to 2022 as well

2022-09-13 20:31 UTC, danieldeleo commented on udfs/community/cw_array_compact.sqlx
> +);
```suggestion
);

```

2022-09-13 20:31 UTC, danieldeleo commented on udfs/community/cw_array_compact.sqlx
> +);
Add trailing newlines to all other files as well

2022-09-21 04:24 UTC, shevek-google approved these changes

2022-09-21 12:43 UTC, danieldeleo commented on udfs/community/test_cases.js
> +            `CAST(1 AS INT64)`
```suggestion
            `"TestStr123456"`,
		        `"Str"`,
		        `CAST(1 AS INT64)`,
            `CAST(1 AS INT64)`
```

2022-09-21 12:45 UTC, danieldeleo commented on udfs/community/test_cases.js
> +generate_udf_test("cw_instr4", [
Please add all your tests to end of this file

2022-09-21 12:46 UTC, danieldeleo requested changes
Will merge after comments addressed

2022-09-21 12:51 UTC, danieldeleo commented on udfs/community/README.md
> +
these are empty

2022-09-21 12:52 UTC, danieldeleo commented on udfs/community/README.md
> +```
empty

2022-09-21 12:54 UTC, danieldeleo commented on udfs/community/README.md
> +```
empty

2022-09-21 12:54 UTC, danieldeleo commented on udfs/community/README.md
> +```
empty

2022-09-21 18:00 UTC, danieldeleo commented on udfs/community/test_cases.js
> +            `CAST(1 AS INT64)`
```suggestion
            `"TestStr123456"`,
		        `"Str"`,
		        `CAST(1 AS INT64)`,
            `CAST(1 AS INT64)`
```

2022-09-21 18:02 UTC, danieldeleo approved these changes

2022-09-21 18:10 UTC, merged